language: ruby
rvm:
- 2.4.1

before_script:
  - chmod +x ./script/cibuild.sh

script: ./script/cibuild.sh

branches:
  only:
    - gh-pages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
