

# Site settings
title: Nicholas Nooney's Blog
author: Nicholas Nooney
email: nicholasnooney@gmail.com
description: >
  A Collection of Ideas and Writings
baseurl: ""
url: "https://blog.nicholasnooney.com"

permalink: none

# Site settings for jekyll-theme-nn
favicon: favicon.png
logo: logo-blue.png
logo_alt: "The Square Nooney Logo"

github_username: nnooney
gitlab_username: nnooney
twitter_username: nicholasnooney
linkedin_username: nicholasnooney

# The excerpt separator determines what content belongs in the excerpt of a post
# and what does not belong. Content before this literal will be included in the
# excerpt.
excerpt_separator: <!-- excerpt separator -->

# The relative url to a page which contains an index of the site's contents.
index_url: /posts

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-nn
plugins:
  - jekyll-feed
include:
  - _pages
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - readme.md
  - env

strict_front_matter: true

# Plugin settings
jekyll-groupby:
  permalink: ":group/:name.html"
  groups:
    - name: "series"
      layout: "group"
    - name: "category"
      layout: "group"
    - name: "tags"
      layout: "group"

assets:
  destination: "/assets/generated"
  raw_precompile: [ "favicon.png" ]
